/**
 * Ukrainian (uk) translation of the Static Channel Analysis window catalog.
 * Mirrors the exact shape of shared/strings/static-analysis.ts — same keys and order.
 */
export const staticAnalysis = {
  windowTitle: 'Статичний аналіз каналу',
  heading: 'Статичний аналіз каналу',
  subtitle: 'Запустіть інструмент Roku для статичного аналізу каналу на своєму каналі.',

  toolStatusChecking: 'Перевірка оновлень…',
  toolStatusDownloading: 'Завантаження інструмента аналізу…',
  toolStatusReady: 'Інструмент аналізу готовий',
  toolStatusReadyUpdated: 'Інструмент аналізу оновлено',
  toolStatusError: (message: string): string => `Не вдалося підготувати інструмент аналізу: ${message}`,
  retryBtn: 'Повторити',
  toolInfoBtnTitle: 'Про інструмент аналізу',
  toolInfoModalTitle: 'Про інструмент аналізу',
  toolInfoModalBodyHtml:
    'Статичний аналіз запускає власний інструмент командного рядка Roku, <code class="sca-inline-code">sca-cmd</code>, для вашого запакованого каналу, щоб виявити проблеми сертифікаційного типу — застарілі API, проблеми з маніфестом, інтеграцію рекламного фреймворку та інше — перш ніж надсилати канал до Channel Store. Roku Dev Studio не постачає цей інструмент; він завантажується від Roku під час першого відкриття цього вікна і повторно перевіряється на оновлення щоразу, коли ви відкриваєте його знову.',

  javaChecking: 'Перевірка Java…',
  javaVersionLabel: (version: string): string => `Java ${version}`,
  javaAvailable: (version: string): string => (version ? `Java знайдено (${version})` : 'Java знайдено'),
  javaMissing: 'Java Не Знайдено',
  installJavaLink: 'Отримати Java',
  javaInfoBtnTitle: 'Про вимогу до Java',
  javaInfoModalTitle: 'Про вимогу до Java',
  javaInfoModalBodyHtml:
    "<code class=\"sca-inline-code\">sca-cmd</code> — це програма на Java, і для роботи потрібне встановлене середовище виконання Java 21 або новішої версії на цьому комп'ютері. Roku Dev Studio лише виявляє Java — вона ніколи не встановлює й не оновлює її за вас.",
  javaInfoRequiredLabel: 'Потрібно',
  javaInfoRequiredValue: 'Java 21 або новіша версія',
  javaInfoDetectedLabel: 'Виявлено',

  channelFileHeading: 'Файл Каналу',
  chooseFileBtn: 'Вибрати Файл Каналу…',
  clearFileTitle: 'Очистити Вибраний Файл',
  dropzoneLabel: 'Або перетягніть файл .zip сюди',
  chooseFileDialogTitle: 'Вибрати .zip каналу',
  filterChannelZip: 'Zip каналу',

  optionsHeading: 'Параметри',
  severityLabel: 'Рівень серйозності',
  severityInfo: 'Інформація',
  severityWarning: 'Попередження',
  severityError: 'Помилка',
  categoriesLabel: 'Категорії',
  categoryUncategorized: 'Без категорії',
  categoryUncategorizedDesc: 'Проблеми, які не належать до жодної іншої категорії.',
  categoryDeprecatedComponents: 'Застарілі компоненти',
  categoryDeprecatedComponentsDesc: 'Компоненти SceneGraph, які Roku визнала застарілими.',
  categoryDeprecatedApis: 'Застарілі API',
  categoryDeprecatedApisDesc: 'API BrightScript, які Roku визнала застарілими.',
  categoryManifest: 'Маніфест',
  categoryManifestDesc: 'Проблеми з файлом маніфесту вашого каналу.',
  categoryRaf: 'RAF',
  categoryRafDesc: 'Перевірки інтеграції з Roku Advertising Framework.',
  categoryRed: 'RED',
  categoryRedDesc: 'Перевірки в категорії сертифікації RED компанії Roku.',
  categoryPackage: 'Пакет',
  categoryPackageDesc: 'Як структуровано пакет (zip) вашого каналу.',

  analyzeBtn: 'Аналізувати',
  cancelBtn: 'Скасувати',
  analyzingLabel: 'Аналіз…',
  consoleOutputLabel: 'Вивід консолі',

  resultsHeading: 'Результати',
  summaryErrors: (n: number): string => `${n} помилк${n === 1 ? 'а' : 'и'}`,
  summaryWarnings: (n: number): string => `${n} попередження`,
  summaryInfo: (n: number): string => `${n} інформаційних`,
  tableHeaderSeverity: 'Рівень серйозності',
  tableHeaderCategory: 'Категорія',
  tableHeaderMessage: 'Повідомлення',
  tableHeaderLocation: 'Розташування',
  viewJsonBtn: 'Показати JSON',
  jsonModalTitle: 'Звіт статичного аналізу — JSON',
  saveJsonBtn: 'Зберегти…',
  saveJsonDialogTitle: 'Зберегти звіт статичного аналізу',
  noReportFallbackNote: 'Структурований звіт не знайдено — показано необроблений вивід інструмента.',
  malformedReportNote: 'Не вдалося прочитати файл звіту — показано необроблений вивід інструмента.',
  noIssuesFound: 'Проблем не знайдено.',
  expandDetailsTitle: 'Показати деталі',
  collapseDetailsTitle: 'Сховати деталі',
  certRequirementsLabel: 'Вимоги сертифікації',
  documentationLabel: 'Документація',

  runCancelled: 'Аналіз скасовано.',
  runTimedOut: 'Час очікування аналізу минув.',
  runFailed: (message: string): string => `Аналіз не вдався: ${message}`,

  errorTitles: {
    'network-unreachable': 'Мережа недоступна',
    'cdn-non-200': 'Не вдалося завантажити',
    'disk-full': 'Недостатньо місця на диску',
    'permission-denied': 'Відмовлено в доступі',
    'unexpected-archive-layout': 'Неочікуваний пакет інструмента',
    'java-not-found': 'Java не знайдено',
    'java-check-failed': 'Перевірка Java не вдалася',
    'java-incompatible': 'Несумісна версія Java',
    'invalid-input-path': 'Файл не знайдено',
    'invalid-input-package': 'Недійсний пакет каналу',
    'spawn-failed': 'Не вдалося запустити інструмент аналізу',
    'sca-tool-crashed': 'Інструмент аналізу дав збій',
    timeout: 'Час очікування аналізу минув',
    cancelled: 'Аналіз скасовано',
    'report-missing': 'Звіт не було створено',
    'report-malformed': 'Не вдалося прочитати звіт',
    'tool-not-ready': 'Інструмент аналізу ще не готовий'
  }
} as const;
