/**
 * Romanian (ro) translation of the Static Channel Analysis window catalog.
 * Mirrors the exact shape of shared/strings/static-analysis.ts — same keys and order.
 */
export const staticAnalysis = {
  windowTitle: 'Analiză statică a canalului',
  heading: 'Analiză statică a canalului',
  subtitle: 'Rulează instrumentul Roku de Analiză Statică a Canalului pe canalul tău.',

  toolStatusChecking: 'Se verifică actualizările…',
  toolStatusDownloading: 'Se descarcă instrumentul de analiză…',
  toolStatusReady: 'Instrumentul de analiză este pregătit',
  toolStatusReadyUpdated: 'Instrumentul de analiză a fost actualizat',
  toolStatusError: (message: string): string => `Instrumentul de analiză nu a putut fi pregătit: ${message}`,
  retryBtn: 'Reîncearcă',
  toolInfoBtnTitle: 'Despre Instrumentul de Analiză',
  toolInfoModalTitle: 'Despre Instrumentul de Analiză',
  toolInfoModalBodyHtml:
    'Analiza statică rulează propriul instrument de linie de comandă al Roku, <code class="sca-inline-code">sca-cmd</code>, asupra canalului tău împachetat pentru a detecta probleme de tip certificare — API-uri depreciate, probleme de manifest, integrare cu framework-ul de publicitate și altele — înainte să trimiți la Channel Store. Roku Dev Studio nu livrează acest instrument; este descărcat de la Roku prima dată când deschizi această fereastră și verificat din nou pentru actualizări de fiecare dată când o deschizi.',

  javaChecking: 'Se verifică Java…',
  javaVersionLabel: (version: string): string => `Java ${version}`,
  javaAvailable: (version: string): string => (version ? `Java detectat (${version})` : 'Java detectat'),
  javaMissing: 'Java Nu a Fost Găsit',
  installJavaLink: 'Obține Java',
  javaInfoBtnTitle: 'Despre Cerința Java',
  javaInfoModalTitle: 'Despre Cerința Java',
  javaInfoModalBodyHtml:
    '<code class="sca-inline-code">sca-cmd</code> este un program Java și are nevoie de un mediu de execuție Java 21 sau o versiune mai nouă instalat pe acest computer pentru a funcționa. Roku Dev Studio doar detectează Java — nu îl instalează și nu îl actualizează niciodată pentru tine.',
  javaInfoRequiredLabel: 'Necesar',
  javaInfoRequiredValue: 'Java 21 sau o versiune mai nouă',
  javaInfoDetectedLabel: 'Detectat',

  channelFileHeading: 'Fișierul Canalului',
  chooseFileBtn: 'Alege Fișierul Canalului…',
  clearFileTitle: 'Șterge Fișierul Selectat',
  dropzoneLabel: 'Sau trage un fișier .zip aici',
  chooseFileDialogTitle: 'Alege un .zip al canalului',
  filterChannelZip: 'Zip al canalului',

  optionsHeading: 'Opțiuni',
  severityLabel: 'Severitate',
  severityInfo: 'Informație',
  severityWarning: 'Avertisment',
  severityError: 'Eroare',
  categoriesLabel: 'Categorii',
  categoryUncategorized: 'Fără categorie',
  categoryUncategorizedDesc: 'Probleme care nu se încadrează în nicio altă categorie.',
  categoryDeprecatedComponents: 'Componente depreciate',
  categoryDeprecatedComponentsDesc: 'Componente SceneGraph pe care Roku le-a marcat ca depreciate.',
  categoryDeprecatedApis: 'API-uri depreciate',
  categoryDeprecatedApisDesc: 'API-uri BrightScript pe care Roku le-a marcat ca depreciate.',
  categoryManifest: 'Manifest',
  categoryManifestDesc: 'Probleme cu fișierul manifest al canalului tău.',
  categoryRaf: 'RAF',
  categoryRafDesc: 'Verificări de integrare cu Roku Advertising Framework.',
  categoryPackage: 'Pachet',
  categoryPackageDesc: 'Modul în care este structurat pachetul (zip) canalului tău.',
  categoryChannelStore: 'Channel Store',
  categoryChannelStoreDesc: 'Cerințe pentru listarea în Channel Store.',
  categoryAuthentication: 'Autentificare',
  categoryAuthenticationDesc: 'Verificări ale fluxurilor de autentificare și asociere a contului canalului tău.',
  categoryBilling: 'Facturare',
  categoryBillingDesc: 'Verificări ale fluxurilor de achiziții în canal și facturare.',
  categoryDeepLinking: 'Deep Linking',
  categoryDeepLinkingDesc: 'Verificări ale implementării deep linking a canalului tău.',
  categoryAnalytics: 'Analiză',
  categoryAnalyticsDesc: 'Verificări ale integrării analizei și telemetriei.',
  categoryPerformance: 'Performanță',
  categoryPerformanceDesc: 'Verificări ale problemelor de performanță din canalul tău.',
  categoryMonitoring: 'Monitorizare',
  categoryMonitoringDesc: 'Verificări ale integrării monitorizării și verificărilor de stare.',

  analyzeBtn: 'Analizează',
  cancelBtn: 'Anulează',
  analyzingLabel: 'Se analizează…',
  consoleOutputLabel: 'Rezultat Consolă',

  resultsHeading: 'Rezultate',
  summaryErrors: (n: number): string => `${n} Eroar${n === 1 ? 'e' : 'i'}`,
  summaryWarnings: (n: number): string => `${n} Avertisment${n === 1 ? '' : 'e'}`,
  summaryInfo: (n: number): string => `${n} Informații`,
  allCategoriesOption: 'Toate Categoriile',
  categoryFilterLabel: 'Filtrează după Categorie',
  noFilterMatchNote: 'Nicio problemă nu corespunde filtrului curent.',
  tableHeaderSeverity: 'Severitate',
  tableHeaderCategory: 'Categorie',
  tableHeaderMessage: 'Mesaj',
  tableHeaderLocation: 'Locație',
  viewJsonBtn: 'Vezi JSON',
  jsonModalTitle: 'Raport de analiză statică — JSON',
  saveJsonBtn: 'Salvează…',
  saveJsonDialogTitle: 'Salvează Raportul de Analiză Statică',
  noReportFallbackNote: 'Nu s-a găsit un raport structurat — se afișează rezultatul brut al instrumentului.',
  malformedReportNote: 'Fișierul raportului nu a putut fi citit — se afișează rezultatul brut al instrumentului.',
  noIssuesFound: 'Nu au fost găsite probleme.',
  expandDetailsTitle: 'Arată Detaliile',
  collapseDetailsTitle: 'Ascunde Detaliile',
  certRequirementsLabel: 'Cerințe de Certificare',
  documentationLabel: 'Documentație',

  runCancelled: 'Analiză anulată.',
  runTimedOut: 'Analiza a expirat.',
  runFailed: (message: string): string => `Analiza a eșuat: ${message}`,

  errorTitles: {
    'network-unreachable': 'Rețea inaccesibilă',
    'cdn-non-200': 'Descărcare eșuată',
    'disk-full': 'Spațiu insuficient pe disc',
    'permission-denied': 'Permisiune refuzată',
    'unexpected-archive-layout': 'Pachet de instrument neașteptat',
    'java-not-found': 'Java nu a fost găsit',
    'java-check-failed': 'Verificarea Java a eșuat',
    'java-incompatible': 'Versiune Java incompatibilă',
    'invalid-input-path': 'Fișierul nu a fost găsit',
    'invalid-input-package': 'Pachet de canal invalid',
    'spawn-failed': 'Instrumentul de analiză nu a putut fi pornit',
    'sca-tool-crashed': 'Instrumentul de analiză s-a blocat',
    timeout: 'Analiza a expirat',
    cancelled: 'Analiză anulată',
    'report-missing': 'Nu a fost generat niciun raport',
    'report-malformed': 'Raportul nu a putut fi citit',
    'tool-not-ready': 'Instrumentul de analiză nu este încă pregătit'
  }
} as const;
