#!/usr/bin/env node
/**
 * Transpile all .ts sources to dist/ (mirrors paths). No typecheck here — run `npm run typecheck`.
 */
import esbuild from 'esbuild';
import { readdirSync, statSync, existsSync, mkdirSync, readFileSync, writeFileSync, cpSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = __dirname;
const dist = join(root, 'dist');

/** Single source of truth: package.json `version` → published as `PACKAGE_VERSION` on the API. */
function writePackageVersionTs() {
  const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'));
  const body = `/**
 * Auto-generated by build.mjs from package.json \`version\` — do not edit.
 */
export const PACKAGE_VERSION: string = ${JSON.stringify(pkg.version)};
`;
  mkdirSync(join(root, 'lib'), { recursive: true });
  writeFileSync(join(root, 'lib', 'package-version.ts'), body);
}

writePackageVersionTs();

function walk(dir) {
  const out = [];
  if (!existsSync(dir)) return out;
  for (const name of readdirSync(dir)) {
    if (name === 'node_modules' || name === 'dist') continue;
    const p = join(dir, name);
    const st = statSync(p);
    if (st.isDirectory()) out.push(...walk(p));
    else if (p.endsWith('.ts')) out.push(p);
  }
  return out;
}

const top = ['index.ts', 'cli.ts', 'ecp.ts', 'relay-client.ts']
  .map((f) => join(root, f))
  .filter((p) => existsSync(p));
const rest = walk(join(root, 'lib')).concat(walk(join(root, 'examples')));
const entryPoints = [...new Set([...top, ...rest])];

mkdirSync(dist, { recursive: true });

await esbuild.build({
  entryPoints,
  outdir: dist,
  outbase: root,
  platform: 'node',
  format: 'cjs',
  target: 'node18',
  logLevel: 'info',
  sourcemap: true,
});

/** Copy the static Roku Fiddle assets (source/*.brs, components/*.brs|xml)
 * from the repo-root `roku-components/fiddle/` into `dist/roku-components/fiddle/`
 * so the published package is self-contained. The Fiddle zip builder reads
 * these at runtime via `readFiddleAsset(...)`. */
function copyFiddleRokuAssets() {
  const src = join(root, '..', '..', 'roku-components', 'fiddle');
  if (!existsSync(src)) {
    console.warn('build.mjs: roku-components/fiddle not found at', src, '— Fiddle zip builder will fail at runtime.');
    return;
  }
  const dest = join(dist, 'roku-components', 'fiddle');
  cpSync(src, dest, { recursive: true });
  console.log('build.mjs: copied Fiddle Roku assets →', 'dist/roku-components/fiddle');
}
copyFiddleRokuAssets();
