/**
 * Polish (pl) translation of the Static Channel Analysis window catalog.
 * Mirrors the exact shape of shared/strings/static-analysis.ts — same keys and order.
 */
export const staticAnalysis = {
  windowTitle: 'Statyczna analiza kanału',
  heading: 'Statyczna analiza kanału',
  subtitle: 'Uruchom narzędzie Roku do Statycznej Analizy Kanału na swoim kanale.',

  toolStatusChecking: 'Sprawdzanie aktualizacji…',
  toolStatusDownloading: 'Pobieranie narzędzia analizy…',
  toolStatusReady: 'Narzędzie analizy jest gotowe',
  toolStatusReadyUpdated: 'Narzędzie analizy zostało zaktualizowane',
  toolStatusError: (message: string): string => `Nie udało się przygotować narzędzia analizy: ${message}`,
  retryBtn: 'Spróbuj ponownie',
  toolInfoBtnTitle: 'O narzędziu analizy',
  toolInfoModalTitle: 'O narzędziu analizy',
  toolInfoModalBodyHtml:
    'Statyczna analiza uruchamia własne narzędzie wiersza poleceń Roku, <code class="sca-inline-code">sca-cmd</code>, na spakowanym kanale, aby wykryć problemy w stylu certyfikacji — przestarzałe API, problemy z manifestem, integrację z frameworkiem reklamowym i inne — przed wysłaniem do Channel Store. Roku Dev Studio nie dostarcza tego narzędzia; jest ono pobierane od Roku przy pierwszym otwarciu tego okna i sprawdzane pod kątem aktualizacji przy każdym kolejnym otwarciu.',

  javaChecking: 'Sprawdzanie Javy…',
  javaVersionLabel: (version: string): string => `Java ${version}`,
  javaAvailable: (version: string): string => (version ? `Wykryto Javę (${version})` : 'Wykryto Javę'),
  javaMissing: 'Nie Znaleziono Javy',
  installJavaLink: 'Pobierz Javę',
  javaInfoBtnTitle: 'O wymaganiu Javy',
  javaInfoModalTitle: 'O wymaganiu Javy',
  javaInfoModalBodyHtml:
    '<code class="sca-inline-code">sca-cmd</code> jest programem w Javie i wymaga zainstalowanego środowiska Java 21 lub nowszego na tym komputerze, aby działać. Roku Dev Studio tylko wykrywa Javę — nigdy nie instaluje jej ani nie aktualizuje za Ciebie.',
  javaInfoRequiredLabel: 'Wymagane',
  javaInfoRequiredValue: 'Java 21 lub nowsza',
  javaInfoDetectedLabel: 'Wykryto',

  channelFileHeading: 'Plik Kanału',
  chooseFileBtn: 'Wybierz Plik Kanału…',
  clearFileTitle: 'Wyczyść Wybrany Plik',
  dropzoneLabel: 'Lub przeciągnij tutaj plik .zip',
  chooseFileDialogTitle: 'Wybierz plik .zip kanału',
  filterChannelZip: 'Plik zip kanału',

  optionsHeading: 'Opcje',
  severityLabel: 'Ważność',
  severityInfo: 'Informacja',
  severityWarning: 'Ostrzeżenie',
  severityError: 'Błąd',
  categoriesLabel: 'Kategorie',
  categoryUncategorized: 'Bez kategorii',
  categoryUncategorizedDesc: 'Problemy, które nie należą do żadnej innej kategorii.',
  categoryDeprecatedComponents: 'Przestarzałe komponenty',
  categoryDeprecatedComponentsDesc: 'Komponenty SceneGraph uznane przez Roku za przestarzałe.',
  categoryDeprecatedApis: 'Przestarzałe API',
  categoryDeprecatedApisDesc: 'API BrightScript uznane przez Roku za przestarzałe.',
  categoryManifest: 'Manifest',
  categoryManifestDesc: 'Problemy z plikiem manifestu Twojego kanału.',
  categoryRaf: 'RAF',
  categoryRafDesc: 'Kontrole integracji z Roku Advertising Framework.',
  categoryRed: 'RED',
  categoryRedDesc: 'Kontrole w kategorii certyfikacji RED firmy Roku.',
  categoryPackage: 'Pakiet',
  categoryPackageDesc: 'Sposób zorganizowania pakietu (zip) Twojego kanału.',

  analyzeBtn: 'Analizuj',
  cancelBtn: 'Anuluj',
  analyzingLabel: 'Analizowanie…',
  consoleOutputLabel: 'Wyjście konsoli',

  resultsHeading: 'Wyniki',
  summaryErrors: (n: number): string => `${n} błąd${n === 1 ? '' : 'y'}`,
  summaryWarnings: (n: number): string => `${n} ostrzeżeni${n === 1 ? 'e' : 'a'}`,
  summaryInfo: (n: number): string => `${n} informacji`,
  tableHeaderSeverity: 'Ważność',
  tableHeaderCategory: 'Kategoria',
  tableHeaderMessage: 'Komunikat',
  tableHeaderLocation: 'Lokalizacja',
  viewJsonBtn: 'Pokaż JSON',
  jsonModalTitle: 'Raport analizy statycznej — JSON',
  saveJsonBtn: 'Zapisz…',
  saveJsonDialogTitle: 'Zapisz raport analizy statycznej',
  noReportFallbackNote: 'Nie znaleziono ustrukturyzowanego raportu — wyświetlono surowe dane wyjściowe narzędzia.',
  malformedReportNote: 'Nie udało się odczytać pliku raportu — wyświetlono surowe dane wyjściowe narzędzia.',
  noIssuesFound: 'Nie znaleziono żadnych problemów.',
  expandDetailsTitle: 'Pokaż Szczegóły',
  collapseDetailsTitle: 'Ukryj Szczegóły',
  certRequirementsLabel: 'Wymagania Certyfikacji',
  documentationLabel: 'Dokumentacja',

  runCancelled: 'Analiza anulowana.',
  runTimedOut: 'Analiza przekroczyła limit czasu.',
  runFailed: (message: string): string => `Analiza nie powiodła się: ${message}`,

  errorTitles: {
    'network-unreachable': 'Sieć niedostępna',
    'cdn-non-200': 'Pobieranie nie powiodło się',
    'disk-full': 'Za mało miejsca na dysku',
    'permission-denied': 'Odmowa dostępu',
    'unexpected-archive-layout': 'Nieoczekiwany pakiet narzędzia',
    'java-not-found': 'Nie znaleziono Javy',
    'java-check-failed': 'Sprawdzanie Javy nie powiodło się',
    'java-incompatible': 'Niezgodna wersja Javy',
    'invalid-input-path': 'Nie znaleziono pliku',
    'invalid-input-package': 'Nieprawidłowy pakiet kanału',
    'spawn-failed': 'Nie udało się uruchomić narzędzia analizy',
    'sca-tool-crashed': 'Narzędzie analizy uległo awarii',
    timeout: 'Analiza przekroczyła limit czasu',
    cancelled: 'Analiza anulowana',
    'report-missing': 'Nie wygenerowano raportu',
    'report-malformed': 'Nie udało się odczytać raportu',
    'tool-not-ready': 'Narzędzie analizy nie jest jeszcze gotowe'
  }
} as const;
