/**
 * Latin American Spanish (neutral) translation of the Static Channel Analysis window catalog.
 * Mirrors the exact shape of shared/strings/static-analysis.ts — same keys and order.
 */
export const staticAnalysis = {
  windowTitle: 'Análisis estático del canal',
  heading: 'Análisis estático del canal',
  subtitle: 'Ejecute la herramienta de Análisis Estático de Canales de Roku en su canal.',

  toolStatusChecking: 'Buscando actualizaciones…',
  toolStatusDownloading: 'Descargando la herramienta de análisis…',
  toolStatusReady: 'Herramienta de análisis lista',
  toolStatusReadyUpdated: 'Herramienta de análisis actualizada',
  toolStatusError: (message: string): string => `No se pudo preparar la herramienta de análisis: ${message}`,
  retryBtn: 'Reintentar',
  toolInfoBtnTitle: 'Acerca de la Herramienta de Análisis',
  toolInfoModalTitle: 'Acerca de la Herramienta de Análisis',
  toolInfoModalBodyHtml:
    'El análisis estático ejecuta la propia herramienta de línea de comandos de Roku, <code class="sca-inline-code">sca-cmd</code>, sobre su canal empaquetado para detectar problemas de tipo certificación — APIs obsoletas, problemas de manifiesto, integración del framework de publicidad y más — antes de enviarlo a la Channel Store. Roku Dev Studio no distribuye esta herramienta; se descarga de Roku la primera vez que abre esta ventana y se vuelve a comprobar si hay actualizaciones cada vez que la abre de nuevo.',

  javaChecking: 'Buscando Java…',
  javaVersionLabel: (version: string): string => `Java ${version}`,
  javaAvailable: (version: string): string => (version ? `Java detectado (${version})` : 'Java detectado'),
  javaMissing: 'Java No Encontrado',
  installJavaLink: 'Obtener Java',
  javaInfoBtnTitle: 'Acerca del Requisito de Java',
  javaInfoModalTitle: 'Acerca del Requisito de Java',
  javaInfoModalBodyHtml:
    '<code class="sca-inline-code">sca-cmd</code> es un programa Java y necesita un entorno de ejecución Java 21 o más reciente instalado en esta máquina para funcionar. Roku Dev Studio solo detecta Java — nunca lo instala ni lo actualiza por usted.',
  javaInfoRequiredLabel: 'Requerido',
  javaInfoRequiredValue: 'Java 21 o más reciente',
  javaInfoDetectedLabel: 'Detectado',

  channelFileHeading: 'Archivo del Canal',
  chooseFileBtn: 'Elegir Archivo del Canal…',
  clearFileTitle: 'Quitar Archivo Seleccionado',
  dropzoneLabel: 'O arrastre un archivo .zip aquí',
  chooseFileDialogTitle: 'Elegir un .zip del canal',
  filterChannelZip: 'Zip del canal',

  optionsHeading: 'Opciones',
  severityLabel: 'Gravedad',
  severityInfo: 'Info',
  severityWarning: 'Advertencia',
  severityError: 'Error',
  categoriesLabel: 'Categorías',
  categoryUncategorized: 'Sin categoría',
  categoryUncategorizedDesc: 'Problemas que no encajan en ninguna otra categoría.',
  categoryDeprecatedComponents: 'Componentes obsoletos',
  categoryDeprecatedComponentsDesc: 'Componentes SceneGraph que Roku ha marcado como obsoletos.',
  categoryDeprecatedApis: 'APIs obsoletas',
  categoryDeprecatedApisDesc: 'APIs de BrightScript que Roku ha marcado como obsoletas.',
  categoryManifest: 'Manifiesto',
  categoryManifestDesc: 'Problemas con el archivo de manifiesto de su canal.',
  categoryRaf: 'RAF',
  categoryRafDesc: 'Verificaciones de integración con Roku Advertising Framework.',
  categoryRed: 'RED',
  categoryRedDesc: 'Verificaciones de la categoría de certificación RED de Roku.',
  categoryPackage: 'Paquete',
  categoryPackageDesc: 'Cómo está estructurado el paquete (zip) de su canal.',

  analyzeBtn: 'Analizar',
  cancelBtn: 'Cancelar',
  analyzingLabel: 'Analizando…',
  consoleOutputLabel: 'Salida de la Consola',

  resultsHeading: 'Resultados',
  summaryErrors: (n: number): string => `${n} Error${n === 1 ? '' : 'es'}`,
  summaryWarnings: (n: number): string => `${n} Advertencia${n === 1 ? '' : 's'}`,
  summaryInfo: (n: number): string => `${n} Info`,
  allCategoriesOption: 'Todas las Categorías',
  categoryFilterLabel: 'Filtrar por Categoría',
  noFilterMatchNote: 'Ningún problema coincide con el filtro actual.',
  tableHeaderSeverity: 'Gravedad',
  tableHeaderCategory: 'Categoría',
  tableHeaderMessage: 'Mensaje',
  tableHeaderLocation: 'Ubicación',
  viewJsonBtn: 'Ver JSON',
  jsonModalTitle: 'Informe de Análisis Estático — JSON',
  saveJsonBtn: 'Guardar…',
  saveJsonDialogTitle: 'Guardar Informe de Análisis Estático',
  noReportFallbackNote: 'No se encontró un informe estructurado — se muestra la salida sin procesar de la herramienta.',
  malformedReportNote: 'No se pudo leer el archivo del informe — se muestra la salida sin procesar de la herramienta.',
  noIssuesFound: 'No se encontraron problemas.',
  expandDetailsTitle: 'Mostrar Detalles',
  collapseDetailsTitle: 'Ocultar Detalles',
  certRequirementsLabel: 'Requisitos de Certificación',
  documentationLabel: 'Documentación',

  runCancelled: 'Análisis cancelado.',
  runTimedOut: 'El análisis superó el tiempo de espera.',
  runFailed: (message: string): string => `El análisis falló: ${message}`,

  errorTitles: {
    'network-unreachable': 'Red no disponible',
    'cdn-non-200': 'Error al descargar',
    'disk-full': 'No hay suficiente espacio en disco',
    'permission-denied': 'Permiso denegado',
    'unexpected-archive-layout': 'Paquete de herramienta inesperado',
    'java-not-found': 'No se encontró Java',
    'java-check-failed': 'Falló la verificación de Java',
    'java-incompatible': 'Versión de Java incompatible',
    'invalid-input-path': 'Archivo no encontrado',
    'invalid-input-package': 'Paquete de canal no válido',
    'spawn-failed': 'No se pudo iniciar la herramienta de análisis',
    'sca-tool-crashed': 'La herramienta de análisis falló',
    timeout: 'El análisis superó el tiempo de espera',
    cancelled: 'Análisis cancelado',
    'report-missing': 'No se generó ningún informe',
    'report-malformed': 'No se pudo leer el informe',
    'tool-not-ready': 'La herramienta de análisis aún no está lista'
  }
} as const;
