/**
 * pt-BR (Brazilian Portuguese) translation of the Static Channel Analysis window catalog.
 * Mirrors the exact shape of shared/strings/static-analysis.ts — same keys and order.
 */
export const staticAnalysis = {
  windowTitle: 'Análise estática do canal',
  heading: 'Análise estática do canal',
  subtitle: 'Execute a ferramenta de Análise Estática de Canal da Roku no seu canal.',

  toolStatusChecking: 'Verificando atualizações…',
  toolStatusDownloading: 'Baixando a ferramenta de análise…',
  toolStatusReady: 'Ferramenta de análise pronta',
  toolStatusReadyUpdated: 'Ferramenta de análise atualizada',
  toolStatusError: (message: string): string => `Não foi possível preparar a ferramenta de análise: ${message}`,
  retryBtn: 'Tentar novamente',
  toolInfoBtnTitle: 'Sobre a Ferramenta de Análise',
  toolInfoModalTitle: 'Sobre a Ferramenta de Análise',
  toolInfoModalBodyHtml:
    'A análise estática executa a própria ferramenta de linha de comando da Roku, o <code class="sca-inline-code">sca-cmd</code>, no seu canal empacotado para detectar problemas do tipo certificação — APIs obsoletas, problemas de manifesto, integração com o framework de publicidade e mais — antes de você enviar para a Channel Store. O Roku Dev Studio não distribui essa ferramenta; ela é baixada da Roku na primeira vez que você abre esta janela, e verificada novamente por atualizações a cada nova abertura.',

  javaChecking: 'Verificando Java…',
  javaVersionLabel: (version: string): string => `Java ${version}`,
  javaAvailable: (version: string): string => (version ? `Java detectado (${version})` : 'Java detectado'),
  javaMissing: 'Java Não Encontrado',
  installJavaLink: 'Obter Java',
  javaInfoBtnTitle: 'Sobre o Requisito de Java',
  javaInfoModalTitle: 'Sobre o Requisito de Java',
  javaInfoModalBodyHtml:
    'O <code class="sca-inline-code">sca-cmd</code> é um programa Java e precisa de um ambiente de execução Java 21 ou mais recente instalado nesta máquina para funcionar. O Roku Dev Studio apenas detecta o Java — ele nunca o instala ou atualiza para você.',
  javaInfoRequiredLabel: 'Necessário',
  javaInfoRequiredValue: 'Java 21 ou mais recente',
  javaInfoDetectedLabel: 'Detectado',

  channelFileHeading: 'Arquivo do Canal',
  chooseFileBtn: 'Escolher Arquivo do Canal…',
  clearFileTitle: 'Limpar Arquivo Selecionado',
  dropzoneLabel: 'Ou arraste um arquivo .zip aqui',
  chooseFileDialogTitle: 'Escolher um .zip do canal',
  filterChannelZip: 'Zip do canal',

  optionsHeading: 'Opções',
  severityLabel: 'Severidade',
  severityInfo: 'Informação',
  severityWarning: 'Aviso',
  severityError: 'Erro',
  categoriesLabel: 'Categorias',
  categoryUncategorized: 'Sem categoria',
  categoryUncategorizedDesc: 'Problemas que não se encaixam em nenhuma outra categoria.',
  categoryDeprecatedComponents: 'Componentes obsoletos',
  categoryDeprecatedComponentsDesc: 'Componentes SceneGraph que a Roku tornou obsoletos.',
  categoryDeprecatedApis: 'APIs obsoletas',
  categoryDeprecatedApisDesc: 'APIs do BrightScript que a Roku tornou obsoletas.',
  categoryManifest: 'Manifesto',
  categoryManifestDesc: 'Problemas com o arquivo de manifesto do seu canal.',
  categoryRaf: 'RAF',
  categoryRafDesc: 'Verificações de integração com o Roku Advertising Framework.',
  categoryRed: 'RED',
  categoryRedDesc: 'Verificações da categoria de certificação RED da Roku.',
  categoryPackage: 'Pacote',
  categoryPackageDesc: 'Como o pacote (zip) do seu canal está estruturado.',

  analyzeBtn: 'Analisar',
  cancelBtn: 'Cancelar',
  analyzingLabel: 'Analisando…',
  consoleOutputLabel: 'Saída do Console',

  resultsHeading: 'Resultados',
  summaryErrors: (n: number): string => `${n} Erro${n === 1 ? '' : 's'}`,
  summaryWarnings: (n: number): string => `${n} Aviso${n === 1 ? '' : 's'}`,
  summaryInfo: (n: number): string => `${n} Informações`,
  allCategoriesOption: 'Todas as Categorias',
  categoryFilterLabel: 'Filtrar por Categoria',
  noFilterMatchNote: 'Nenhum problema corresponde ao filtro atual.',
  tableHeaderSeverity: 'Severidade',
  tableHeaderCategory: 'Categoria',
  tableHeaderMessage: 'Mensagem',
  tableHeaderLocation: 'Local',
  viewJsonBtn: 'Ver JSON',
  jsonModalTitle: 'Relatório de Análise Estática — JSON',
  saveJsonBtn: 'Salvar…',
  saveJsonDialogTitle: 'Salvar Relatório de Análise Estática',
  noReportFallbackNote: 'Não foi encontrado um relatório estruturado — exibindo a saída bruta da ferramenta.',
  malformedReportNote: 'Não foi possível ler o arquivo do relatório — exibindo a saída bruta da ferramenta.',
  noIssuesFound: 'Nenhum problema encontrado.',
  expandDetailsTitle: 'Mostrar Detalhes',
  collapseDetailsTitle: 'Ocultar Detalhes',
  certRequirementsLabel: 'Requisitos de Certificação',
  documentationLabel: 'Documentação',

  runCancelled: 'Análise cancelada.',
  runTimedOut: 'A análise atingiu o tempo limite.',
  runFailed: (message: string): string => `A análise falhou: ${message}`,

  errorTitles: {
    'network-unreachable': 'Rede inacessível',
    'cdn-non-200': 'Falha no download',
    'disk-full': 'Espaço em disco insuficiente',
    'permission-denied': 'Permissão negada',
    'unexpected-archive-layout': 'Pacote de ferramenta inesperado',
    'java-not-found': 'Java não encontrado',
    'java-check-failed': 'Falha na verificação do Java',
    'java-incompatible': 'Versão do Java incompatível',
    'invalid-input-path': 'Arquivo não encontrado',
    'invalid-input-package': 'Pacote de canal inválido',
    'spawn-failed': 'Não foi possível iniciar a ferramenta de análise',
    'sca-tool-crashed': 'A ferramenta de análise travou',
    timeout: 'A análise atingiu o tempo limite',
    cancelled: 'Análise cancelada',
    'report-missing': 'Nenhum relatório foi gerado',
    'report-malformed': 'Não foi possível ler o relatório',
    'tool-not-ready': 'A ferramenta de análise ainda não está pronta'
  }
} as const;
